# Jekyll Defaults

source:      .
destination: ./_site
layouts_dir:     ./_layouts

future:      true
show_drafts: nil
limit_posts: 0
highlighter: pygments

permalink:     date

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
imageurl:    images
url:         http://localhost:4000
lsi:         false

# Custom
